name: Fetch and Store ILS Exchange Rate

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch JSON data
        id: fetch
        run: |
          curl -s "https://v6.exchangerate-api.com/v6/9d90a307165975a4b2958f79/latest/EUR" -o response.json
          cat response.json
        shell: bash

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Transform JSON data
        id: transform
        run: |
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          ILS_RATE=$(jq -r '.conversion_rates.ILS' response.json)
          echo "{\"date\": \"${DATE}\", \"rate\": \"${ILS_RATE}\"}" > transformedData.json
        shell: bash

      - name: Store JSON data in Firebase
        env:
          FIREBASE_API_KEY: AIzaSyCdXQC67xCMtWV4pA6wkMrQflrRgLPG1Q0
          FIREBASE_PROJECT_ID: annual-report-52e9f
        run: |
          DATABASE_URL="https://${{ env.FIREBASE_PROJECT_ID }}.firebaseio.com/eur_ils.json?auth=${{ env.FIREBASE_API_KEY }}"
          curl -X POST -d @transformedData.json "$DATABASE_URL"
        shell: bash
