name: Add Data to Firestore

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  add-to-firestore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set execute permissions
        run: chmod +x ./exchange

      - name: Run executable        
        run: ./exchange
