name: Add Data to Firestore

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  add-to-firestore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Fetch JSON data and Add to Firestore
        env:
          FIREBASE_TOKEN: 1//0359wk9p2597FCgYIARAAGAMSNwF-L9IrVS-rxx1DN_fIZuMTkURAF9tb7-Zs00jKGe7JfkUTQERtl5m-tWECZRkP6SgtN2JPvhc
        run: |
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          ILS_RATE=$(curl -s "https://v6.exchangerate-api.com/v6/9d90a307165975a4b2958f79/latest/EUR" | jq -r '.conversion_rates.ILS')
          echo "{\"date\": \"$DATE\", \"rate\": \"$ILS_RATE\"}" > document.json
          firebase firestore:import document.json --collection=eur_ils --project=annual-report-52e9f --token="${FIREBASE_TOKEN}"
          
