name: Fetch and Store Exchange Rate

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch JSON data
        id: fetch
        run: |
          curl -s "https://v6.exchangerate-api.com/v6/9d90a307165975a4b2958f79/latest/EUR" -o response.json
          cat response.json
        shell: bash

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  

      - name: Install Firebase tools
        run: npm install -g firebase-tools   

      - name: Transform and Store JSON data in Firebase
        env:
          FIREBASE_TOKEN: AIzaSyCdXQC67xCMtWV4pA6wkMrQflrRgLPG1Q0
        run: |
          # Extract the current date and ILS exchange rate
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          ILS_RATE=$(jq -r '.conversion_rates.ILS' response.json)
          echo "{\"date\": \"${DATE}\", \"rate\": \"${ILS_RATE}\"}" > transformedData.json
          
          # Authenticate with Firebase
          firebase auth:login --token "${FIREBASE_TOKEN}"

          # Upload the transformed data to Firebase
          firebase database:push /eur_ils transformedData.json --project annual-report-52e9f
        shell: bash
