name: Fetch and Store ILS Exchange Rate

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch JSON data
        id: fetch
        run: |
          curl -s "https://v6.exchangerate-api.com/v6/9d90a307165975a4b2958f79/latest/EUR" -o response.json
          cat response.json
        shell: bash

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Store JSON data in Firebase
        env:
          FIREBASE_API_KEY: AIzaSyCdXQC67xCMtWV4pA6wkMrQflrRgLPG1Q0
        run: |
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          ILS_RATE=$(jq -r '.conversion_rates.ILS' response.json)
      
          curl -X POST -d '{
           "date": ${{ DATE }},
           "rate": ${{ ILS_RATE }},
          }' 'https://annual-report-52e9f.firebaseio.com/eur_ils.json?auth=AIzaSyCdXQC67xCMtWV4pA6wkMrQflrRgLPG1Q0'
                                      
        shell: bash
