name: Add Data to Firestore

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  add-to-firestore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Firebase credentials
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > firebase_credentials.json

      - name: Verify Firebase credentials file
        run: |
          echo "Checking if credentials file exists..."
          ls -l firebase_credentials.json
          echo "Contents of the credentials file:"
          cat firebase_credentials.json  

      - name: Set execute permissions
        run: chmod +x ./exchange

      - name: Run executable     
        run: ./exchange firebase_credentials.json
